name: phy
dependencies:
  - python=3.5
  - numpy
  - matplotlib
  - scipy
  - h5py
  - pyqt=4
  - pip:
    - vispy
    - requests
    - traitlets
    - tqdm
    - six
    - joblib
    - click
    - git+https://github.com/m-beau/phy_plugins.git
